---
- name: Create Directory to extract the zipped file
  shell: |
    mkdir backend

- name: Copy files
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/

- name: unzip artifacts
  shell: |
    tar -xvzf /home/ubuntu/backend/artifact.tar.gz

- name: Install dependencies and start
  shell: |
    npm i 
    npm run build
    npm run start
